[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["net", "io-util", "macros", "rt-multi-thread", "sync", "signal"] }
anyhow = "1.0.100"